---
- name: Upload Simple File
  hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    file_src: config.json
    file_dest: /usr/src
    mode: 0777
  tasks:
    - name: Upload file config.json
      template:
        src: "{{file_src}}"
        dest: "{{file_dest}}"
        mode: "{{mode}}"
      register: upload_file
      
    - name: Troca texto
      replace:
        path: "{{file_dest}}/{{file_src}}"
        backup: true
        regexp: "development"
        replace: "production"
      when: upload_file is success  

      
    